# Generated by Django 2.2 on 2021-03-09 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210309_2304'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentModel',
        ),
    ]
