# Generated by Django 2.2 on 2021-03-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_studentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmodel',
            name='phone',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='hall_ticket_no',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='phone',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
