# Generated by Django 2.2 on 2021-03-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210310_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexp',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workexp',
            name='start_year',
            field=models.IntegerField(),
        ),
    ]
